### ISSUE TITLE
`ActivationBuffer` used inconsistently re running out of data.

### ISSUE THREAD

**Issue by joelburget** [saprmarks/dictionary_learning#7]
When you run `trainSAE`, it expects to run through all of the data because the line `for step, acts in enumerate(tqdm(activations, total=steps))` simply exits the loop when `StopIteration` is raised. But `evaluate` simply calls `acts = next(activations).to(device)`, so it fails if the data runs out. I think ideally this case should be handled gracefully, but it should at least be documented.

Code:

```
from nnsight import LanguageModel
from dictionary_learning import ActivationBuffer
from dictionary_learning.training import trainSAE
from dictionary_learning.evaluation import evaluate

model = LanguageModel("EleutherAI/pythia-70m-deduped")
submodule = model.gpt_neox.layers[1].mlp
activation_dim = 512
dictionary_size = 16 * activation_dim

data = iter(
    [
        "This is some example data",
        "In real life, for training a dictionary",
        "you would need much more data than this",
    ]
)
buffer = ActivationBuffer(
    data,
    model,
    submodule,
    out_feats=activation_dim,
    n_ctxs=3e4,
)

ae = trainSAE(
    buffer,
    activation_dim,
    dictionary_size,
    lr=3e-4,
    sparsity_penalty=1e-3,
)

buffer = ActivationBuffer(
    iter(["hello", "world"]),
    model,
    submodule,
    out_feats=activation_dim,
    n_ctxs=300,
)

print(evaluate(model, submodule, ae, buffer))
```

Result:
```
joel@simplex ~/c/mamba-sae (main)> python3.11 test.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/joel/code/mamba-sae/dictionary_learning/buffer.py", line 94, in text_batch
    return [
           ^
  File "/Users/joel/code/mamba-sae/dictionary_learning/buffer.py", line 95, in <listcomp>
    next(self.data) for _ in range(batch_size)
    ^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joel/code/mamba-sae/test.py", line 46, in <module>
    print(evaluate(model, submodule, ae, buffer))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/code/mamba-sae/dictionary_learning/evaluation.py", line 119, in evaluate
    acts = next(activations).to(device)
           ^^^^^^^^^^^^^^^^^
  File "/Users/joel/code/mamba-sae/dictionary_learning/buffer.py", line 76, in __next__
    self.refresh()
  File "/Users/joel/code/mamba-sae/dictionary_learning/buffer.py", line 164, in refresh
    self._refresh_std()
  File "/Users/joel/code/mamba-sae/dictionary_learning/buffer.py", line 121, in _refresh_std
    with self.model.invoke(self.text_batch(), truncation=True, max_length=self.ctx_len) as invoker:
                           ^^^^^^^^^^^^^^^^^
  File "/Users/joel/code/mamba-sae/dictionary_learning/buffer.py", line 98, in text_batch
    raise StopIteration("End of data stream reached")
StopIteration: End of data stream reached
```

**Comment by saprmarks** [comment]
Thanks -- I've now added a more informative error for this.
