### ISSUE TITLE
Tensors must have same number of dimensions: got 2 and 3

### ISSUE THREAD

**Issue by joelburget** [saprmarks/dictionary_learning#9]
Using basically the example code from README.md:

```
from nnsight import LanguageModel
from dictionary_learning import ActivationBuffer
from dictionary_learning.training import trainSAE
from dictionary_learning.evaluation import evaluate

model = LanguageModel("EleutherAI/pythia-70m-deduped")
submodule = model.gpt_neox.layers[1].mlp
activation_dim = 512
dictionary_size = 16 * activation_dim

data = iter(
    [
        "This is some example data",
        "In real life, for training a dictionary",
        "you would need much more data than this",
    ]
)
buffer = ActivationBuffer(
    data,
    model,
    submodule,
    out_feats=activation_dim,
    n_ctxs=3e4,
)

ae = trainSAE(
    buffer,
    activation_dim,
    dictionary_size,
    lr=3e-4,
    sparsity_penalty=1e-3,
)
```

Output:
```
(env) root@12702e9f3980:/workspace/mamba-sae# python3 test.py
Resolving data files: 100%|██████████████████████████████████████████| 30/30 [00:06<00:00,  4.89it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
0it [00:00, ?it/s]You're using a GPTNeoXTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
0it [00:17, ?it/s]
Traceback (most recent call last):
  File "/workspace/mamba-sae/test.py", line 33, in <module>
    ae = trainSAE(
  File "/workspace/mamba-sae/dictionary_learning/training.py", line 180, in trainSAE
    for step, acts in enumerate(tqdm(activations, total=steps)):
  File "/workspace/mamba-sae/env/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/workspace/mamba-sae/dictionary_learning/buffer.py", line 76, in __next__
    self.refresh()
  File "/workspace/mamba-sae/dictionary_learning/buffer.py", line 164, in refresh
    self._refresh_std()
  File "/workspace/mamba-sae/dictionary_learning/buffer.py", line 130, in _refresh_std
    self.activations = t.cat([self.activations, hidden_states.value.to(self.device)], dim=0)
RuntimeError: Tensors must have same number of dimensions: got 2 and 3
```

The problem is that `self.activations.shape` is `torch.Size([0, 512])` while `hidden_states.value.shape` is `torch.Size([512, 128, 512])`. I'm not sure which is right.

**Comment by saprmarks** [comment]
I'm guessing that this is related to https://github.com/saprmarks/dictionary_learning/issues/8 since the current implementation simultaneously removes padding tokens at the same time it flattens over batch and sequence positions. Let's discuss there.
